### ISSUE TITLE
Has your host been deleted?

### ISSUE THREAD

**Issue by gallegonovato** [bogachenko/filterlist#1]
Good evening:

First of all thank you for your time and help. And for your great work.

I would like to ask you a question if I may.

I was using your host with address https://raw.githubusercontent.com/bogachenko/filterlist/master/hosts . But I see that now there is no such host.

I don't know if I delete it. If you are going to put it again or you are going to create another one? Or if there is a way to recover it to use it again?

Thank you very much for your help and time

Receive a warm embrace

**Comment by bogachenko** [comment]
[Removed as unnecessary](https://github.com/bogachenko/filterlist/commit/92027248b231b0ad06a5f0290894ff5571f8dbe3), I used to use it to block all the shit on my phone (I used AdAway) and my computer (by editing the hosts file), but now it doesn't make sense. Now I use [Adguard Home](https://adguard.com/en/adguard-home/overview.html), set it up to block ads on all my devices: on my computer, on my TV, on my phone, and on my mother's phone. Using Adguad Home is much more practical (at least for me), [here is a list of my rules](https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoFL.dns) that I use to block shit in Adguard Home. 

PS: FYI Adguard Home is the Russian analogue of [Pi-Hole](https://pi-hole.net/), only it is better.

**Comment by bogachenko** [comment]
I'm slowly returning the [hosts file](https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoBL.hosts), if you're interested. On Chinese devices, it is impossible without it, hundreds of advertising and tracking requests to rush into the network request log thereby creating confusion and an unreadable appearance.
