### ISSUE TITLE
anti-AD.net

### ISSUE THREAD

**Issue by RicoHeat** [bogachenko/filterlist#2]
The following: 
/^(.+[_.-])?ad[sxv]?([\d]+)?[_.-]/

is causing this website `https://anti-ad.net/` to be blocked and additionally preventing the anti-AD list from updating.

This is there GitHub page:
https://github.com/privacy-protection-tools/anti-AD

**Comment by bogachenko** [comment]
Although there will be a lot of such false positives, a huge number of domains with `-ad.net`. I will delete this. Add better to yourself or refuse to use the sheet. I hid this repository in my profile many months ago, it is for private use.
