### ISSUE TITLE
facebook.com/messages

### ISSUE THREAD

**Issue by gir489** [bogachenko/filterlist#22]
I can not use facebook messenger or watch movies in full screen with this on. When I do, messenger refuses to load, and when I try to fullscreen the video, the page refreshes.

**Comment by bogachenko** [comment]
I don't have a Facebook account, so I'll leave it open for now, and then I'll try to create one. Later.

**Comment by gir489** [comment]
Any update on this?

**Comment by bogachenko** [comment]
Well, I created a fake account and I can’t reproduce this problem. Give me your adblock config.

**Comment by gir489** [comment]
The only other fitler I have on besides the default AdBlock config is https://github.com/bogachenko/fuckfuckadblock.

For default, I have Ad Blocking, Other, Language Specific and Custom, which is the two mentioned, this one and fuck fuck adblock.

I have a feeling simply making the account might not be enough, you might need to add friends and then try it that way, I haven't tested this since making the thread, because I had not re-added this filter for a while because it used to be named something else and stopped updating, but then found it again, and the issue cropped back up.

**Comment by bogachenko** [comment]
I will not add friends. Added a couple of bots - nothing in Facebook Messenger (in the full screen), they respond and nothing reboots. With Facebook Watch (also in the full screen), nothing is the same.

Do not want to provide a config, provide a log.
