### ISSUE TITLE
This list and the Fuck Fuckadblock list

### ISSUE THREAD

**Issue by SnowFK** [bogachenko/filterlist#28]
Can I add this list together with Fuck Fuckadblock, on uBlock Origin or are they the same?

**Comment by bogachenko** [comment]
You can. And no, they are not the same, `Fuck Fuckadblock` removes pop-up windows (scripts) and removes adblock disable messages. `bogachenko's Filter List` exclusively blocks domains with ads, trackers, mining and other shit.
