### ISSUE TITLE
Blocking Kaspersky Websites

### ISSUE THREAD

**Issue by LethalAspect** [bogachenko/filterlist#3]
Hello, 
I want to ask on why kaspersky websites are listed in the [bogachenkoPF](bogachenkoPF.txt) filterlist?
If its something about russia or spyware then tell please me I'm curious 👀

**Comment by bullik01** [comment]
It's russian spyware

ср, 17 мая 2023 г., 15:23 Lethal ***@***.***>:

**Comment by LethalAspect** [comment]
Since I already have your answer, I'm gonna close this. Its not russian spyware but thanks for the reason anyways!

**Comment by LethalAspect** [comment]
If you want to see why, I would suggest looking at this [post](https://www.kaspersky.com/blog/kaspersky-in-the-shitstorm/19794/).

**Comment by bogachenko** [comment]
As the person above said, it collects information (like any other antivirus), and it abuses it a lot.  I don’t know how it is all over the world, but in Russia there is very frequent news that the creator Evgeny Kaspersky is collaborating with the FSB and similar structures (active cooperation with Roskomnadzor, it's terrible. Sites are blocked for one-two).  In addition, Russian banks are actively implanting (without the ability to disable) this antivirus, and as soon as I enter the banking application, it scans my phone.

In general, in principle, I don’t campaign for the use of an antivirus, but if I began to choose, then my choice would fall on Nod32 or Dr Web.

**Comment by LethalAspect** [comment]
I get why you dont want to use it but as I said before there was never proof to begin with. But wait, when does it abuse collecting information?

> funny to read why kaspersky antivirus is not a spy, on the kaspersky website

I can give you what they said there if you dont want to visit the site

```
Russian hackers, you say? Is Kaspersky really working with Russian intelligence agencies?

We help law enforcement agencies (globally, not only in Russia), but with only one thing —catching cybercriminals.

This collaboration sometimes helps us create, for example, [ransomware decryptors](https://noransom.kaspersky.com/), helping victims recover lost files (free; we don’t get paid for that). We also create other useful things, such as a website one can use to check whether their computer is a part of a botnet.

We’ve never assisted any cyberspies or military intelligence. That would go against our principles. We do not participate in spying.
```

**Comment by LethalAspect** [comment]
But then again, I'm not forcing you to unadd the list or force you to use it. I was just curious.

**Comment by LethalAspect** [comment]
Responding to the edited comment, if you notice none of the articles actually provide any proof.

**Comment by bogachenko** [comment]
It seems to me that you are not completely in control of the situation, it is not necessary to catch them by the hand in order to know that he is actively cooperating with law enforcement agencies. And this is not only about the terrorists and cybercriminals, about whom your article is written, but also about ordinary citizens.

~Have you ever heard about Pavel Durov (and about his VK) and business in Russia?~

**Comment by bogachenko** [comment]
In any case, the topic is closed, as you yourself said, I answered your question.
